---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: ocp-domain
  description: Everything about artists
spec:
  owner: cld-ocpadmin-sg
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ocp-system
spec:
  owner: cld-ocpadmin-sg
  domain: ocp-domain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ocp-component
  description: Artist Lookup testing by OCP Team
  tags:
    - java
    - data
    - ocp
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert    
    - url: https://example.com/console
      title: Console
      icon: console         
  annotations:
    backstage.io/linguist: 'https://github.com/dbacademy/backstage/tree/master/plugins/playlist'
spec:
  type: service
  lifecycle: experimental
  owner: cld-ocpadmin-sg
  system: ocp-system
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
